### PR TITLE
[DRAFT] Qa 1226 Add Kubernetes deployment capabilities

### PR DESCRIPTION
**Pull request by suneel-lean**
**Description of Changes**
* Added deployment and service for the conformance suite
* And other minor fixes

**Types of Changes**

* [ ] Bug fix
* [ ] New feature
* [ ] Performance improvement
* [ ] Documentation update
* [x] Add kubernetes deployment support

**Testing**

* Describe how you verified that your changes work as intended.
* Include details about the types of tests added or executed (unit, integration, end-to-end, etc.)

**Screenshots (if applicable)**

* If visual changes are made, please provide screenshots or screen recordings.

**Additional Notes**

* Are there any potential risks, side-effects, or dependencies to consider? 
* Are there any additional context or instructions for the reviewer?

**Checklist**

* [ ] I have performed sufficient testing.
* [ ] I have updated the documentation accordingly (if applicable).
* [ ] I have considered potential breaking changes or compatibility issues.

### CODE REVIEW

**Comment by amroessam** [comment]
What's pending here?

**Comment by ReshailLean** [comment]
@fortune-mabonga can you review for us please.

@suneel-lean secrets for SA02: https://vault.sa02.leantech.me/ui/vault/secrets/secrets/show/ms/openbanking-access-service-secret

**Review by amroessam — COMMENTED** [review]
What's pending here?

**Review by illia-sh — CHANGES_REQUESTED** [review]
Can you please have a call with DevOps about this change as this looks like a new flow: 
https://www.notion.so/leantech/DevOps-checklist-142ba31b30d44622bc5f9e944950880e

- Which docker registy it's going to use 
- Which k8s cluster use
- How this endpoint will be used "conformance.ae03.leantech.me" 
- Any reason we  are no deploying it via ArgoCD?
- How this repository going to be used? 
- There is no CODEOWNER for this repo
- dockerfile should be with named as Dockerfile and teste with https://github.com/hadolint/hadolint
- Can you please add topic for this repo to view the owner, it can be done here 
 -> https://github.com/leantechnologies/IaC/blob/main/dev/github/csv/topics.csv
- Branch Protection should not allow bypassing rules

**Comment by suneel-lean** [comment]
Closing this pr as I have covered all the requested changes have been addressed in other prs and respective repositories:

With regards to the [comment](https://github.com/leantechnologies/lean-conformance-suite/pull/1#pullrequestreview-1948436317)

1. Any reason we are no deploying it via ArgoCD? This was a draft pr and we did correct it by creating service.yaml file in microservice_configuration repo respectively, [pr](https://github.com/leantechnologies/microservices-configuration/pull/6300) (I had scheduled call with Fortune and got the changes reviewed twice) and also followed the [golden path](https://www.notion.so/leantech/4a9d8c2fd503437fa2b737d60d3dcc29?v=fbe93a31ce814dfca8d5d918d9f01d78)
2. Updated the topics.csv in IaC repo, [pr_IaC](https://github.com/leantechnologies/IaC/pull/1035)
3. Added code owners in lean-conformance-suite in a new [pr_lcs](https://github.com/leantechnologies/lean-conformance-suite/pull/4)

**Pull request closed without merging**
